# USERS


@usersId = 68d8077534ff7f42505b20e7
@usersUrl = users

### register
POST http://localhost:3030/{{usersUrl}}/register HTTP/1.1
Content-Type: application/json

{
  "name": "jef",
  "lastname": "lugo",
  "username": "jef",
  "email": "vbncvyuitya<das>@gmaisda.com",
  "password": "123456"
}

### login
POST http://localhost:3030/{{usersUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "jefito@gmail.com",
  "password": "123456"
}

### get current user info
GET http://localhost:3030/{{usersUrl}}/me HTTP/1.1
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQzMzI4Y2I1NmMyYmRiMzEzMTkxZjQiLCJpYXQiOjE3NTg5ODkzMjcsImV4cCI6MTc1OTU5NDEyN30.FUnHlRBWdLQU5X3KdhmSrjYQQGfIGsNC9KivmkLeftA"

### get public user info
GET http://localhost:3030/{{usersUrl}}/people/{{usersId}} HTTP/1.1
Content-Type: application/json

{
  "email": "vbncvyuitya<das>@gmaisda.com",
  "password": "123456"
}

### update user info
PUT http://localhost:3030/{{usersUrl}}/{{usersId}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bombon changed",
  "weight": 80,
  "left": 0,
  "make": 0
}

### delete user
DELETE http://localhost:3030/{{usersUrl}}/{{usersId}} HTTP/1.1


# SAVED BREADS


@savedBreadsId = 66875af841b533f95cf45f1b
@savedBreadsUrl = savedSaltyBreads

###
GET http://localhost:3030/{{savedBreadsUrl}} HTTP/1.1

###
GET http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1

###
POST http://localhost:3030/{{savedBreadsUrl}} HTTP/1.1
Content-Type: application/json

{
  "date": "asdasd",
  "breads": [
    {
      "name": "Maiz",
      "weight": 80,
      "left": 0,
      "make": 0
    }
  ]
}

###
PUT http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1
Content-Type: application/json

{
  "date": "zxcv",
  "breads": [
    {
      "name": "Bonbom",
      "weight": 80,
      "left": 0,
      "make": 0
    }
  ]
}

###
DELETE http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1


# RESETS


# @savedBreadsId = 66875af841b533f95cf45f1b
@resetsUrl = sweetResets

###
GET http://localhost:3030/{{resetsUrl}} HTTP/1.1